create sequence hibernate_sequence start 1 increment 1;

create table tb_reference (
                              id int8 generated by default as identity,
                              name text not null,
                              primary key (id)
);

create table tb_role (
                         id int8 not null,
                         name varchar(255),
                         primary key (id)
);

create table tb_tree (
                         id int8 generated by default as identity,
                         single_name         varchar(255) not null
                        ,popular_name        varchar(255)
                        ,family              varchar(255) not null
                        ,botanical_name      varchar(255) not null
                        ,name_meaning        text
                        ,general_description text not null
                        ,special_description text
                        ,where_occurs        text
                        ,ecological_info     text
                        ,phenological_info   text
                        ,propagation         text
                        ,management_guide    text
                        ,utilities           text
                        ,cultural_importance text
                        ,primary key (id)
);

create table tb_users (
                          id int8 not null,
                          name varchar(255),
                          password varchar(255),
                          username varchar(255),
                          primary key (id)
);

create table tb_users_roles (
                                app_user_id int8 not null,
                                roles_id int8 not null
);

create table tree_reference (
                                tree_id int8 not null,
                                reference_id int8 not null,
                                primary key (tree_id, reference_id)
);

alter table if exists tb_tree
    add constraint UK_b1a39qbgrk9un4q1sipr1fgs3 unique (single_name);

alter table if exists tb_users_roles
    add constraint FK2xk9iuhi1faf7fg5qc1gi2e6a
        foreign key (roles_id)
            references tb_role;

alter table if exists tb_users_roles
    add constraint FK15kdxdgr6c8rfscrmjgmj9is5
        foreign key (app_user_id)
            references tb_users;

alter table if exists tree_reference
    add constraint FKs35ho6i6mpfp2oiii3qnmjxh4
        foreign key (reference_id)
            references tb_reference;

alter table if exists tree_reference
    add constraint FKn2npva89m1jdygmn8eoi9i220
        foreign key (tree_id)
            references tb_tree;

INSERT INTO tb_tree(single_name,popular_name,family,botanical_name,name_meaning,general_description,special_description,where_occurs,ecological_info,phenological_info,propagation,management_guide,utilities,cultural_importance)
VALUES (
           'Ameixa',
           'ambuy (MG), ameixa-da-bahia (BA), ameixa-da-terra, ameixa-de-espinho (PE, RN), ameixa-do-brasil (SP), ameixa-do-para, ameixeira, ameixeira-de-espinho, espinheiro-de-ameixa.'
       ,'Olacaceae'
       ,'Ximenia americana L.'
       ,null
       ,'Arvore pequena ou arbusto espinhoso, de 3-4 m de altura, de casca avermelhada a cinzenta, fina, pouco rugosa a lisa, muito adstringente. Folhas pecioladas, glabras, oblongas, alternas, inteiras, pequenas. Flores amareladas, aromáticas, com cheiro da flor de laranjeira, peludas, com as pétalas notável e elegantemente recurvadas, dispostas em racimos curtos axilares ou terminais. O fruto e uma drupa amarelo-alaranjada, ovoide, com ca. de 2 cm de diâmetro, contendo polpa aromática, mais ou menos doce, adstringente, pouco aquosa, comestível, envolvendo uma semente com amêndoa-branca. Fornece boa madeira de cor rósea, compacta e
        leve, muito elástica, bastante durável, fácil de trabalhar.'
       ,'Durante parte da estação seca, destaca-se pela copa verde no meio da caatinga seca. Tem espinhos. A copa se mostra mais aberta do que a do juazeiro (outro sempre-verde da caatinga). Da frutos comestíveis no final da estação seca.'
       ,'No Brasil, do Para até a Bahia, Minas Gerais, Goiás e Mato Grosso. No Ceara e frequente em todos os tabuleiros, no sertão, e também na região das dunas, mas ausente nas serras frescas'
       ,'Planta verde durante boa parte da estação seca, ocorre em agrupamentos. Os frutos são muito apreciados pelos animais silvestres e as abelhas tiram pólen e néctar das flores, isso na época do ano quando são poucas as plantas em floração na caatinga.'
       ,'Mantem as folhas verdes durante uma parte da estação seca, depois as perde e antes das primeiras chuvas renova a folhagem e floresce (novembro), seguida pela frutificação.'
       ,'A ameixa pode ser propagada por sementes ou estacas.'
       ,null
       ,'Madeira: a madeira é própria para cabos de ferramentas e de instrumentos agrícolas. Alimentação humana: os frutos comestíveis e saborosos são uma importante fonte de vitaminas e sais minerais para os habitantes da caatinga, numa época do ano com poucas frutas. A polpa do fruto de um suco muito gostoso, mas tem de ser tirado com cuidado para não cortar o caroço. Poderia ser utilizado na fabricação de sorvetes e doces. Medicina caseira: usa-se a casca como adstringente, quer em banhos prolongados nas menstruações excessivas, quer em cozimento na lavagem de feridas ou ainda sob a forma de pó na cicatrização de úlceras e feridas. As sementes dão 70% de óleo viscoso, amarelo e purgativo. Restauração florestal: em reflorestamento, para enriquecer capoeiras e recuperar a vegetação de áreas degradadas. Sistemas agroflorestais: em pomares mistos de frutíferas nativas da caatinga. Uso na composição de quebra-ventos, faixas arbóreas entre plantações e acompanhando cercas e limites. Abelhas: fornece pólen e néctar para as abelhas na estação seca. Aplicações industriais: a essência das flores, com cheiro da flor da laranjeira, poderia ser usada na indústria de perfumaria. Outras aplicações: para sombreamento de estradas rurais.'
       ,'a ameixa e uma das plantas que sofreram, como toda a vegetação da caatinga, com o preconceito da inferioridade do Nordeste. Assim, suas utilidades não foram até agora valorizadas Nordeste e as potencialidades dessa planta são pouco estudadas e pouco utilizadas. Ela é uma planta de múltiplos usos, inclusive para a alimentação humana direta (frutos) e indireta (mel de abelha), para a saúde humana, para usos da madeira e tem potencial como fonte de renda (perfumaria). Deve ser mais estudado também o emprego como "estaca viva'''' para cercas, como planta ornamental. o fato de a ameixa dar fruto saboroso no meio estação seca, sem irrigação, faz dela uma espécie adequada para ser usada em pomares mistos de frutíferas nativas, reflorestamento e enriquecimento de capoeiras, plantio ao longo das estradas, perto das casas e em faixas arbóreas entre plantações ou acompanhando cercas ou limites. Dessa forma, a produção de frutas, tão importantes para a alimentação humana no meio da estação seca, pode ocorrer sem precisar de irrigação e sem ocupar as terras mais férteis.');

INSERT INTO tb_reference (name) VALUES ('BRAGA, Renato: Plantas do Nordeste, especialmente do Ceará. 1ª edição, 1953.2ª edição modificada, 1960.4ª edição. Editora Universitária da UFRN. Coleção Mossoroence. Vol. CCCXV.Natal – RN.');
INSERT INTO tb_reference (name) VALUES ( 'DUQUE, José Guimarães: Solo e água no polígono das secas. Fortaleza – CE.Brasil. 2ª edição, 1951.');
INSERT INTO tb_reference (name) VALUES ( 'DUQUE, José Guimarães: O Nordeste e as lavouras xerófilas. Coleção Mossoroence.Vol.CXLIII,3ª edição, Natal – RN.1980. 1ª edição, 1964.2ª edição, 1973. ');
INSERT INTO tb_reference (name) VALUES ( 'FERRI, Mário Guimarães:Vegetação Brasileira.Belo Horizonte:Ed. Itatiaia. São Paulo. Ed. Da Universidade de São Paulo, 1980.');
INSERT INTO tb_reference (name) VALUES ( 'ATLAS DO MEIO AMBIENTE DO BRASIL.Brasília – DF, 1994.Copyright:Empresa Brasileira de Pesquisa Agropecuária.EMBRAPA');
INSERT INTO tb_reference (name) VALUES ( 'ECOSSISTEMAS e Potencialidades dos Recursos Naturais do Nordeste. SUDENE – UFPE. Edição preliminar.Recife,1989');
INSERT INTO tb_reference (name) VALUES ( 'OS ECOSSISTEMAS Brasileiros e os Principais Macrovetores de Desenvolvimento. Subsídios ao Planejamento da Gestão Ambiental. Ministério do Meio Ambiente, dos Recursos Hídricos e da Amazônia Legal - Secretaria de Coordenação dos Assuntos do Meio Ambiente. Brasília - DF, 1995.');
INSERT INTO tb_reference (name) VALUES ( 'INDEX KEWENSIS: An Enumeration of the Genera and Species of Flowering Plants. From the time of Linnaeus to the year 1885 inclusive together with their authors names, the works in which they were first published, their native countries and their synonymes. Volume II. Oxford. At the Clarendon Press, 1895. ');
INSERT INTO tb_reference (name) VALUES ( 'MENDES, Benedito Vasconcelos: Biodiversidade e Desenvolvimento Sustentável do Semi-árido. Fortaleza: SEMACE, 1997');
INSERT INTO tb_reference (name) VALUES ( 'SALOMÃO, A.L.F.; SILVA, LL. da: Angico Vermelho - uma opção entre as espécies florestais nativas Piptadenia macrocarpa Benth. Leguminosae Mimosoidae. Brasil Florestal. Ano 10. N° 41, 1980, p. 45-50. ');
INSERT INTO tb_reference (name) VALUES ( 'PROJETO PNUD/FAO/IBAMA/BRA/87 /007: Desenvolvimento Florestal lntegrado no Nordeste: I Reunião sobre Desenvolvimento do Setor Florestal no Nordeste. Documentos e Relatório Final, 10-12 de Novembro de 1993. Recife -PE. ');
INSERT INTO tb_reference (name) VALUES ( 'SHARMA, P.N.; SILVA, A.D.S: Native Forest (Caatinga) Watershed Management for Runoff lnducement for Irrigation. Forest Ecology and Management. 18. p. 73-84, 1987.');
INSERT INTO tb_reference (name) VALUES ( 'SCHACHT, W.H.; LONG,J.N.; GOBENA, A.: Aboveground biomass accumulation in coppicing woodland, northeast Brazil, 1992.');
INSERT INTO tb_reference (name) VALUES ( 'UNIVERSIDADE ABERTA - Ensino a distância. Curso: Desenvolvimento Sustentável do Semi-Árido. Fascículos N°.1-12, 1995.Fundação Demócrito Rocha');
INSERT INTO tb_reference (name) VALUES ( 'LORENZI, Harri: Árvores brasileiras - Manual de identificação e Cultivo de Plantas Nativas do Brasil. Nova Odessa- SP. Editora Plantarum, 1992');
INSERT INTO tb_reference (name) VALUES ( 'ALVES, Sandra M.C.; LOPES, Rachel N. de S.: Plantas medicinais mais usadas na Região Botânica. Crato-CE, 1997. Ponta do Mel, Areia Branca - RN. Trabalho apresentado no XLVIII Congresso Nacional de Botânica. Crato-CE, 1997');
INSERT INTO tb_reference (name) VALUES ( 'ALBUQUERQUE, Severino G de BANDEIRA, George Ricardo L.:Effect of thinning and slashing on forage phytomass from a caatinga of Petrolina , Pernambuco, Brazil.Pesq. agropec.bras..Brasília.V.30.Nº.6.p.885-891,jun.1995');
INSERT INTO tb_reference (name) VALUES ( 'CHECKLIST das Plantas do Nordeste. Subconjunto de famílias revisadas. Base de Dados CNIP – Centro Nordestino de informações sobre plantas. Disponível em: <http://umbuzeiro.cnip.org.br/db/pnerev/index.html>. Acesso em: nov.2000.');
INSERT INTO tb_reference (name) VALUES ( 'LIMA, D. de Andrade: A vegetação in Atlas Nacional do Brasil, Inst. Brasil. Geogr. E Est – IBGE.Const.Nac.Geogr.,1966.');
INSERT INTO tb_reference (name) VALUES ( 'SOCIEDADE BOTÂNICA DO BRASIL: Manual sobre métodos de estudo florístico e fitossociológico – ecossistema caatinga, Dezembro 1992');
INSERT INTO tb_reference (name) VALUES ( 'JOLY, Aylthon Brandão: Conheça a vegetação brasileira. São Paulo, Ed. Univ. de São Paulo e Polígno, 1970.');
INSERT INTO tb_reference (name) VALUES ( 'OLIVEIRA, José G. B. de et al.: Observações preliminares da fenologia de plantas da caatinga na estação ecológica de Aiuaba, Ceará. Coleção Mossoroense.Série B. Nº 538, 1988');

